/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as MyApplicationRouteImport } from './routes/my-application'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSeedAdminRouteImport } from './routes/api/public/seed-admin'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationRoute = MyApplicationRouteImport.update({
  id: '/my-application',
  path: '/my-application',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedAdminRoute = ApiPublicSeedAdminRouteImport.update({
  id: '/api/public/seed-admin',
  path: '/api/public/seed-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/my-application': typeof MyApplicationRoute
  '/signin': typeof SigninRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/my-application': typeof MyApplicationRoute
  '/signin': typeof SigninRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/my-application': typeof MyApplicationRoute
  '/signin': typeof SigninRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/my-application'
    | '/signin'
    | '/api/public/seed-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/my-application'
    | '/signin'
    | '/api/public/seed-admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/my-application'
    | '/signin'
    | '/api/public/seed-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  MyApplicationRoute: typeof MyApplicationRoute
  SigninRoute: typeof SigninRoute
  ApiPublicSeedAdminRoute: typeof ApiPublicSeedAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-application': {
      id: '/my-application'
      path: '/my-application'
      fullPath: '/my-application'
      preLoaderRoute: typeof MyApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-admin': {
      id: '/api/public/seed-admin'
      path: '/api/public/seed-admin'
      fullPath: '/api/public/seed-admin'
      preLoaderRoute: typeof ApiPublicSeedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  MyApplicationRoute: MyApplicationRoute,
  SigninRoute: SigninRoute,
  ApiPublicSeedAdminRoute: ApiPublicSeedAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
